version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: shop-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: gallery
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mariadb", "-u", "root", "-p1234", "-e", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: wldrh1023/shop-backend:latest
    container_name: shop-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/gallery
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: wldrh1023/shop-frontend:latest
    container_name: shop-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mariadb_data:
